### ISSUE TITLE
Issues: --isoAnnotLite and --report

### ISSUE THREAD

**Issue by tay45** [ConesaLab/SQANTI3#118]
Hello,

I ran the sqanti3_qc using the below command line.
 
sqanti3_qc.py collapsed.gtf gencode.v30.chr_patch_hapl_scaff.annotation.gtf GRCh38.p12.genome.fa \
--cage_peak hg38.cage_peak_phase1and2combined_coord.bed \
--polyA_peak atlas.clusters.2.0.GRCh38.96.bed \
--polyA_motif_list mouse_and_human.polyA_motif.txt \
-o out_sqanti -d sqanti3 -fl collapsed.abundance.tsv --cpus 4 -n 10 --genename \
--isoAnnotLite --gff3 Homo_sapiens_GRCh38_Ensembl_86.gff3 \
-c intropolis.v1.hg19_with_liftover_to_hg38.tsv.min_count_10.modified --report both

But, the tappAS gff3 file was not produced although I used the --isoAnnotLite and the --gff3 options.

And also, even though I used the --report both, only report.pdf was generated without the report.html.

I attached the log as below. Could you help me to resolve these issues? Thank you. 

R scripting front-end version 4.1.1 (2021-08-10)
Write arguments to /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/nalm6e/sqanti3/out_sqanti.params.txt...
**** Running SQANTI3...
launching worker on on /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/nalm6e/sqanti3/out_sqanti_splits/0/collapsed.gtf.split0....
launching worker on on /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/nalm6e/sqanti3/out_sqanti_splits/1/collapsed.gtf.split1....
**** Parsing provided files....
Reading genome fasta /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/supporting_files/GRCh38.p12.genome.fa....
launching worker on on /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/nalm6e/sqanti3/out_sqanti_splits/2/collapsed.gtf.split2....
**** Parsing provided files....
Reading genome fasta /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/supporting_files/GRCh38.p12.genome.fa....
launching worker on on /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/nalm6e/sqanti3/out_sqanti_splits/3/collapsed.gtf.split3....
**** Parsing provided files....
Reading genome fasta /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/supporting_files/GRCh38.p12.genome.fa....
launching worker on on /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/nalm6e/sqanti3/out_sqanti_splits/4/collapsed.gtf.split4....
**** Parsing provided files....
Reading genome fasta /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/supporting_files/GRCh38.p12.genome.fa....
launching worker on on /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/nalm6e/sqanti3/out_sqanti_splits/5/collapsed.gtf.split5....
**** Parsing provided files....
Reading genome fasta /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/supporting_files/GRCh38.p12.genome.fa....
launching worker on on /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/nalm6e/sqanti3/out_sqanti_splits/6/collapsed.gtf.split6....
**** Parsing provided files....
Reading genome fasta /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/supporting_files/GRCh38.p12.genome.fa....
launching worker on on /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/nalm6e/sqanti3/out_sqanti_splits/7/collapsed.gtf.split7....
**** Parsing provided files....
Reading genome fasta /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/supporting_files/GRCh38.p12.genome.fa....
launching worker on on /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/nalm6e/sqanti3/out_sqanti_splits/8/collapsed.gtf.split8....
**** Parsing provided files....
Reading genome fasta /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/supporting_files/GRCh38.p12.genome.fa....
launching worker on on /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/nalm6e/sqanti3/out_sqanti_splits/9/collapsed.gtf.split9....
**** Parsing provided files....
Reading genome fasta /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/supporting_files/GRCh38.p12.genome.fa....
**** Parsing provided files....
Reading genome fasta /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/supporting_files/GRCh38.p12.genome.fa....
Skipping aligning of sequences because GTF file was provided.
.
.
.

[1] "SQANTI3 report successfully generated!"
.
.
.
Error in file(con, "w") : cannot open the connection
Calls: <Anonymous> -> <Anonymous> -> write_utf8 -> writeLines -> file
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
Traceback (most recent call last):
  File "/opt/SQANTI3/4.2/SQANTI3-4.2/sqanti3_qc.py", line 2509, in <module>
    main()
  File "/opt/SQANTI3/4.2/SQANTI3-4.2/sqanti3_qc.py", line 2499, in main
    combine_split_runs(args, split_dirs)
  File "/opt/SQANTI3/4.2/SQANTI3-4.2/sqanti3_qc.py", line 2344, in combine_split_runs
    if subprocess.check_call(cmd, shell=True)!=0:
  File "/opt/SQANTI3/4.2/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/SQANTI3/4.2/bin/Rscript /opt/SQANTI3/4.2/SQANTI3-4.2/utilities/SQANTI3_report.R /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/nalm6e/sqanti3/out_sqanti_classification.txt /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/nalm6e/sqanti3/out_sqanti_junctions.txt /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/Pipelines/IsoSeq3_Sqanti3/nalm6e/sqanti3/out_sqanti.params.txt /opt/SQANTI3/4.2/SQANTI3-4.2/utilities False both' returned non-zero exit status 1.

**Comment by aarzalluz** [comment]
Hi @tay45,

Please try replacing IsoAnnotLite with the newer version (v2.7.1, which you can download [here](https://isoannot.tappas.org/isoannot-lite/)), and let us know if that fixes the issue.

In addition, make sure that your directory structure is not generating errors in SQ3. I see that you have several nested directories for SQANTI (`/opt/SQANTI3/4.2/SQANTI3-4.2/`) and that may be causing the error when parallelized threads are merged to return an output -which seems to be one of the issues, since you have an error in `combine_split_runs`.

Best,


Ángeles
