### ISSUE TITLE
augustus.hints.gtf doesn't appear to be a GTF file

### ISSUE THREAD

**Issue by zmz1988** [ConesaLab/SQANTI3#129]
Hi Liz,

I'm trying to use SQANTI3 to add some long-read evidence or new isolform information from our Isoseq data, by using the .gtf file generated by Braker2 or Tsebra. But somehow the .gtf file can't be recognised as a gtf when I ran the command

`python /home/user/SQANTI3-4.2/sqanti3_qc.py ../C_final_23022022_new_hapog_braker_annotation/long_read_protocol/cupcake.collapsed.gff ./tsebra/C_final_23022022_new_hapog_tsebra.gtf ./C_final_23022022_new_hapog.fasta.mod.MAKER.masked \
--SR_bam bam_file.fofn \
-c ../01_trimmed_filtered_Illumina_RNAseq/C_final_23022022_new_hapog_SJ.out.tab \
-fl ../C_final_23022022_new_hapog_braker_annotation/long_read_protocol/cupcake.collapsed.abundance.txt \
--cpus 20 \
--report both \
-o C_final_23022022_new_hapog `

Error message
```
(SQANTI3.env) [user@node15 C_final_23022022_new_hapog_braker_annotation]$ sh sqanti3_run.sh
R scripting front-end version 4.1.2 (2021-11-01)
Write arguments to /annotation/C_final_23022022_new_hapog_braker_annotation/C_final_23022022_new_hapog.params.txt...
**** Running SQANTI3...
**** Parsing provided files....
Reading genome fasta /annotation/C_final_23022022_new_hapog_braker_annotation/C_final_23022022_new_hapog.fasta.mod.MAKER.masked....
Skipping aligning of sequences because GTF file was provided.

Indels will be not calculated since you ran SQANTI3 without alignment step (SQANTI3 with gtf format as transcriptome input).
FASTA index file /annotation/C_final_23022022_new_hapog_braker_annotation/C_final_23022022_new_hapog.fasta.mod.MAKER.masked.fai created.
**** Predicting ORF sequences...
**** Parsing Reference Transcriptome....
/annotation/C_final_23022022_new_hapog_braker_annotation/tsebra/Can_final_23022022_new_hapog_tsebra.gtf doesn't appear to be a GTF file (GFF not supported by this program)
Traceback (most recent call last):
  File "/home/user/SQANTI3-4.2/sqanti3_qc.py", line 2509, in <module>
    main()
  File "/home/user/SQANTI3-4.2/sqanti3_qc.py", line 2492, in main
    run(args)
  File "/home/user/SQANTI3-4.2/sqanti3_qc.py", line 1887, in run
    refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene = reference_parser(args, list(genome_dict.keys()))
  File "/home/user/SQANTI3-4.2/sqanti3_qc.py", line 664, in reference_parser
    for r in genePredReader(referenceFiles):
  File "/home/user/SQANTI3-4.2/sqanti3_qc.py", line 137, in __init__
    self.f = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/annotation/C_final_23022022_new_hapog_braker_annotation/refAnnotation_C_final_23022022_new_hapog.genePred'
```

And I tried to run `gtfToGenePred` alone befor running `sqanti3_qc.py`

`/home/user/SQANTI3-4.2/utilities/gtfToGenePred ./tsebra/C_final_23022022_new_hapog_tsebra.gtf refAnnotation_C_final_23022022_new_hapog.genePred`
but got error
"./tsebra/C_final_23022022_new_hapog_tsebra.gtf doesn't appear to be a GTF file (GFF not supported by this program)"

I'm not sure what to do, because I checked the .gtf file, it looks ok

```
(SQANTI3.env) [user@node15 C_final_23022022_new_hapog_braker_annotation_pchuckle]$ head -n 10 ./tsebra/C_final_23022022_new_hapog_tsebra.gtf
Chr1_RagTag_p	AUGUSTUS	gene	12743	14596	.	+	.	g_6052
Chr1_RagTag_p	AUGUSTUS	transcript	12743	14596	0.98	+	.	anno1.g5769.t1
Chr1_RagTag_p	AUGUSTUS	start_codon	12743	12745	.	+	0	transcript_id "anno1.g5769.t1"; gene_id "g_6052";
Chr1_RagTag_p	AUGUSTUS	CDS	12743	12896	1	+	0	transcript_id "anno1.g5769.t1"; gene_id "g_6052";
Chr1_RagTag_p	AUGUSTUS	exon	12743	12896	.	+	.	transcript_id "anno1.g5769.t1"; gene_id "g_6052";
Chr1_RagTag_p	AUGUSTUS	intron	12897	12978	1	+	.	transcript_id "anno1.g5769.t1"; gene_id "g_6052";
Chr1_RagTag_p	AUGUSTUS	CDS	12979	13259	1	+	2	transcript_id "anno1.g5769.t1"; gene_id "g_6052";
Chr1_RagTag_p	AUGUSTUS	exon	12979	13259	.	+	.	transcript_id "anno1.g5769.t1"; gene_id "g_6052";
Chr1_RagTag_p	AUGUSTUS	intron	13260	13451	1	+	.	transcript_id "anno1.g5769.t1"; gene_id "g_6052";
Chr1_RagTag_p	AUGUSTUS	CDS	13452	13571	1	+	0	transcript_id "anno1.g5769.t1"; gene_id "g_6052";
```

I had tried to use either augustus.hints.gtf or braker.gtf, and none of them works. Could you please give me some hints on how to solve this issue?

Thanks a lot!

**Comment by zmz1988** [comment]
I got this problem solved by running fix_gtf_ids.py script from tsebra to correct the gene_id and trnascript_id.
