### ISSUE TITLE
classification step assertion error cupcake

### ISSUE THREAD

**Issue by rsalz** [ConesaLab/SQANTI3#13]
Trying to run sqanti3_qc and run into an error once reaching the classification step: 

**** Performing Classification of Isoforms....
Number of classified isoforms: 73118
Traceback (most recent call last):
  File "/mnt/xomics/renees/tools/SQANTI3/sqanti3_qc.py", line 2289, in <module>
    main()
  File "/mnt/xomics/renees/tools/SQANTI3/sqanti3_qc.py", line 2273, in main
    run(args)
  File "/mnt/xomics/renees/tools/SQANTI3/sqanti3_qc.py", line 1724, in run
    write_collapsed_GFF_with_CDS(isoforms_info, corrGTF, corrGTF+'.cds.gff')
  File "/mnt/xomics/renees/tools/SQANTI3/sqanti3_qc.py", line 425, in write_collapsed_GFF_with_CDS
    for r in reader:
  File "/home/renees/.local/lib/python3.7/site-packages/cupcake-9.0.3-py3.7-linux-x86_64.egg/cupcake/io/GFF.py", line 405, in __next__
    return self.read()
  File "/home/renees/.local/lib/python3.7/site-packages/cupcake-9.0.3-py3.7-linux-x86_64.egg/cupcake/io/GFF.py", line 562, in read
    assert raw[2] == 'transcript'
AssertionError

Any idea what could be going wrong here? for the --gff3 parameter I passed the tappas-provided human gff3 file like I normally do.

**Comment by sunshine-lp0** [comment]
Hi,
I got the same error.
How did you solve this problem?

**Comment by rsalz** [comment]
I didn't. I closed the issue because I had separate screens each running SQANTI3 and one of them didn't have this error so I could continue. I maybe should have left it open, I'm also curious as to what caused this

**Comment by sunshine-lp0** [comment]
Thank you! 

I checked and installed all dependencies needed in SQANTI3. All  versions are the latest. And now both SQANTI2 and SQANTI3 can work!

Best wishes

**Comment by FJPardoPalacios** [comment]
Hi,

I don't believe that it has nothing to do with --gff3 parameter.

I'm curious, which parameters did you used for running SQANTI3? Can you take a look at the <output_prefix>_corrected.gtf.cds.gff file that should be find in the output directory?

**Comment by Magdoll** [comment]
Closed unless there's further issues.
