### ISSUE TITLE
Error in simpleLoess

### ISSUE THREAD

**Issue by sum732** [ConesaLab/SQANTI3#164]
Hello !
While running `Sqanti3_qc.py` for one the samples I keep getting following error message:
`Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  : 
  invalid 'x'
Execution halted`

When this is happening, I do not get `.html` and `.pdf` along with `.gff3` and `.isoAnnotLite_stats.txt` are not produced. All the others files are produced. 

This error is happening when I am providing the `-fl` file. If I do not provide the `-fl` parameter i see all the files.

This is not an environment setup issue as in the same env another samples with `-fl` works, no error is shown and all the files are produced. 

Next, I specifically looked at the `fl clount` file and compared with another samples ( that works) and all seems normal: total records are same between two files; I looked at simple stats: `min max, mean, median quartiles` values and expected difference are observed. I am not able to understand the error. 

If any one can provide some insights that would be very helpful.

Below is the extended messages with error:

`summarise()` has grouped output by 'lenCat'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'associated_transcript'. You can override
using the `.groups` argument.
`summarise()` has grouped output by 'associated_transcript'. You can override
using the `.groups` argument.

`Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  : 
  invalid 'x'`

`Execution halted`

`Traceback (most recent call last):`

  `File "Research/Programs/SQANTI3/version_5.1_Release_19_07_2022/SQANTI3-5.1/sqanti3_qc.py", line 2490, in <module>`

    `main()`

  `File "Research/Programs/SQANTI3/version_5.1_Release_19_07_2022/SQANTI3-5.1/sqanti3_qc.py", line 2473, in main`
  `  run(args)`
  `File "Research/Programs/SQANTI3/version_5.1_Release_19_07_2022/SQANTI3-5.1/sqanti3_qc.py", line 2057, in run`
 `   if subprocess.check_call(cmd, shell=True)!=0:`
  `File "/.conda/envs/SQANTI3.env/lib/python3.9/subprocess.py", line 373, in check_call`
  `  raise CalledProcessError(retcode, cmd)`
`subprocess.CalledProcessError: Command '/.conda/envs/SQANTI3.env/bin/Rscript /Research/Programs/SQANTI3`
`/version_5.1_Release_19_07_2022/SQANTI3-5.1/utilities//report_qc/SQANTI3_report.R /with_STAR_SJ_Expression/SQANTI3_QC/sqanti3_qc_2_B01_STAR_SJ_classification.txt /with_STAR_SJ_Expression/SQANTI3_QC/sqanti3_qc_2_B01_STAR_SJ_junctions.txt /with_STAR_SJ_Expression/SQANTI3_QC/sqanti3_qc_2_B01_STAR_SJ.params.txt /Research/Programs/SQANTI3/version_5.1_Release_19_07_2022/SQANTI3-5.1/utilities True both' returned non-zero exit status 1.`

**Comment by sum732** [comment]
after some more testing if I remove `--saturation` parameter I do not see any of the errors and get all the output. So now what is causing saturation plot to fail?

**Comment by aarzalluz** [comment]
Hi @sum732 -thank you for reporting this. We will take a closer look as soon as we can. In the meantime, if running SQ3 without the `--saturation` parameter works for that particular sample, you will need to use that workaround in order to prevent SQ3 from failing.

**Comment by sum732** [comment]
Thanks @aarzalluz for looking into this. For now I am not producing the report with `--saturation`, but it would be vital to have these plots for the publication. Any help will be much appreciated. 
Many thanks in advance.
