### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by veravelasco** [ConesaLab/SQANTI3#19]
Please explain the problem below and how to fix.  Thanks.

Traceback (most recent call last):
  File "/home/CAM/vvelasco/Applications/SQANTI3/sqanti3_qc.py", line 2289, in <module>
    main()
  File "/home/CAM/vvelasco/Applications/SQANTI3/sqanti3_qc.py", line 2273, in main
    run(args)
  File "/home/CAM/vvelasco/Applications/SQANTI3/sqanti3_qc.py", line 1702, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "/home/CAM/vvelasco/Applications/SQANTI3/sqanti3_qc.py", line 594, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/home/CAM/vvelasco/Applications/anaconda3/envs/SQANTI3.env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl /home/CAM/vvelasco/Applications/SQANTI3/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /labs/Wegrzyn/CoAdapTree_Douglasfir/Assembly_comparison/04_Sqanti/GMST/GMST_tmp /labs/Wegrzyn/CoAdapTree_Douglasfir/Assembly_comparison/04_Sqanti/all.fake_genome_corrected.fasta' returned non-zero exit status 1.

**Comment by aarzalluz** [comment]
Issue #11 duplicate.
