### ISSUE TITLE
ArrayMemoryError when calculating TSS ratio

### ISSUE THREAD

**Issue by skudashev** [ConesaLab/SQANTI3#223]
Hello SQANTI3 team, 

I am trying to run SQANTI3 and use short read BAM files for ratio TSS. I have used the same list of BAM files (27 files) for other SQANTI3 runs with similar sized transcript gtfs before but this time am getting a memory error.  1.91 PiB seems like a huge memory requirement. I tried reducing the number of BAMs to 8, but that didn't fix the error. 

```
Using provided BAM files for calculating TSS ratio
...
Traceback (most recent call last):
  File "/opt/SQANTI3-5.1/sqanti3_qc.py", line 2490, in <module>
    main()
  File "/opt/SQANTI3-5.1/sqanti3_qc.py", line 2473, in main
    run(args)
  File "/opt/SQANTI3-5.1/sqanti3_qc.py", line 1858, in run
    isoforms_info, ratio_TSS_dict = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict, corrGTF)
  File "/opt/SQANTI3-5.1/sqanti3_qc.py", line 1521, in isoformClassification
    ratio_TSS_dict = get_ratio_TSS(inside_bed, outside_bed, bams, chr_order)
  File "/opt/SQANTI3-5.1/utilities/short_reads.py", line 185, in get_ratio_TSS
    ratio_rep_df = pandas.merge(ratio_rep_df, merged[['id','ratio_TSS']], on='id')
  File "/opt/anaconda_SQANTI3_env/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 124, in merge
    return op.get_result(copy=copy)
  File "/opt/anaconda_SQANTI3_env/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 773, in get_result
    join_index, left_indexer, right_indexer = self._get_join_info()
  File "/opt/anaconda_SQANTI3_env/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 1026, in _get_join_info
    (left_indexer, right_indexer) = self._get_join_indexers()
  File "/opt/anaconda_SQANTI3_env/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 1000, in _get_join_indexers
    return get_join_indexers(
  File "/opt/anaconda_SQANTI3_env/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 1610, in get_join_indexers
    return join_func(lkey, rkey, count, **kwargs)  # type: ignore[operator]
  File "pandas/_libs/join.pyx", line 48, in pandas._libs.join.inner_join
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 1.91 PiB for an array with shape (268654868768224,) and data type int64
```

```
sqanti3_qc.py --cpus 20 --report pdf --genename --force_id_ignore --aligner_choice minimap2 \
--polyA_motif_list $SQANTI3/data/polyA_motifs/mouse_and_human.polyA_motif.txt \
--CAGE_peak Annotations/human.refTSS.hg38.4.1.bed --SR_bam list_of_SR_bams.txt \
--isoAnnotLite --gff3 $tools/IsoAnnotLite/human_tappas_gencode_annotation_file.gff3 \
--sites GTAG,GCAG,ATAC --dir 2023-08_sqanti3_out $gtf $sequin_gtf $sequin_fa
```
```
sqanti3_qc.py --version
Rscript (R) version 4.2.2 (2022-10-31)
SQANTI3 5.0

```
Appreciate your help, 
Sofia

**Comment by aarzalluz** [comment]
Hi @skudashev,

Have you tried parallelizing with the `--chunks` option? Perhaps that could help (see the [documentation](https://github.com/ConesaLab/SQANTI3/wiki/Running-SQANTI3-Quality-Control#parallelization) for details). 

Otherwise, you should use an even lower number of BAM files, or contact your system administrator for help with memory handling.

Hope that helps,

Ángeles
