### ISSUE TITLE
Strand assertion error in SQANTI3 QC

### ISSUE THREAD

**Issue by dawangran** [ConesaLab/SQANTI3#235]
hello~

I have an error in QC：
Number of classified isoforms: 25571
Traceback (most recent call last):
  File "/hwfssz5/ST_SUPERCELLS/P21Z10200N0090/wangxue/songyumo/software/SQANTI3/sqanti3_qc.py", line 2537, in <module>
    main()
  File "/hwfssz5/ST_SUPERCELLS/P21Z10200N0090/wangxue/songyumo/software/SQANTI3/sqanti3_qc.py", line 2520, in main
    run(args)
  File "/hwfssz5/ST_SUPERCELLS/P21Z10200N0090/wangxue/songyumo/software/SQANTI3/sqanti3_qc.py", line 1892, in run
    write_collapsed_GFF_with_CDS(isoforms_info, corrGTF, corrGTF+'.cds.gff')
  File "/hwfssz5/ST_SUPERCELLS/P21Z10200N0090/wangxue/songyumo/software/SQANTI3/sqanti3_qc.py", line 420, in write_collapsed_GFF_with_CDS
    for r in reader:
  File "/jdfssz1/ST_SUPERCELLS/P21Z10200N0090/Automated/USER/songyumo/software/scisoprep/scripts/SQANTI3-1.6/cDNA_Cupcake/cupcake/io/GFF.py", line 419, in __next__
    return self.read()
  File "/jdfssz1/ST_SUPERCELLS/P21Z10200N0090/Automated/USER/songyumo/software/scisoprep/scripts/SQANTI3-1.6/cDNA_Cupcake/cupcake/io/GFF.py", line 603, in read
    rec = gmapRecord(chr, coverage=None, identity=None, strand=strand, seqid=seqid, geneid=geneid)
  File "/jdfssz1/ST_SUPERCELLS/P21Z10200N0090/Automated/USER/songyumo/software/scisoprep/scripts/SQANTI3-1.6/cDNA_Cupcake/cupcake/io/GFF.py", line 324, in __init__
    assert strand == '+' or strand == '-'
AssertionError
Rscript (R) version 4.2.0 (2022-04-22)

May I ask what causes it?What should be done?
thanks～

**Comment by juanfraitu1** [comment]
In case this is still an issue for anyone, this code removes anything that is not + or - in the strand column:

 awk '$7 != "." || NR < 3' input.gtf > input_corrected.gtf
