### ISSUE TITLE
issues running IsoAnnotLite

### ISSUE THREAD

**Issue by jackhump** [ConesaLab/SQANTI3#26]
I'm trying to run SQANTI with the isoAnnotLite option so I can then run Tappas using my Isoseq data as a functional reference.

It's not clear whether I need to use a reference GTF that matches the IsoAnnot GFF3 - I've tried with both a GENCODE and a RefSeq GTF and I get the same error. Here's my SQANTI command:

```
GTF=all_samples/test/all_samples_filtered_chr21.gtf
COUNT=all_samples/cupcake_filtered/all_samples.demux_fl_count_filtered.csv

export PS1=""; ml anaconda3; CONDA_BASE=$(conda info --base); source $CONDA_BASE/etc/profile.d/conda.sh; ml purge;
conda activate SQANTI3.env; 
export PYTHONPATH=$PYTHONPATH:/sc/arion/projects/ad-omics/data/software/cDNA_Cupcake/sequence;export PYTHONPATH=$PYTHONPATH:/sc/arion/projects/ad-omics/data/software/cDNA_Cupcake/;

python /sc/arion/projects/ad-omics/data/software/SQANTI3/sqanti3_qc.py -t 8 --aligner_choice=minimap2 --dir all_samples/SQANTI3_test/  --out all_samples.cupcake.collapsed.filtered  \
--cage_peak /sc/arion/projects/ad-omics/data/references/hg38_reference/SQANTI3/hg38.cage_peak_phase1and2combined_coord.bed \
--polyA_motif_list /sc/arion/projects/ad-omics/data/references/hg38_reference/SQANTI3/human.polyA.list.txt  \
--fl_count $COUNT \
--gtf $GTF \
 --isoAnnotLite --gff3 /sc/arion/projects/ad-omics/data/references/hg38_reference/RefSeq/Homo_sapiens_GRCh38_RefSeq_78.gff3 \
/sc/arion/projects/ad-omics/data/references/hg38_reference/RefSeq/GRCh38_latest_genomic.gtf \
/sc/hydra/projects/ad-omics/data/references/hg38_reference/hg38.fa 

```

SQANTI runs fine, both ORF prediction and report generation occur without error, but then I get this from IsoAnnot:

```
Running IsoAnnot Lite 1.5...

Reading SQANTI 3 Files and creating an auxiliar GFF...
Reading reference annotation file and creating data variables...
Transforming CDS local positions to genomic position...
Transforming feature local positions to genomic position in GFF3...
Mapping transcript features betweeen GFFs...


	0.00 % of transcripts annotated...

	·Annoted a total of 0 annotation features from reference GFF3 file.
Traceback (most recent call last):
  File "/sc/arion/projects/ad-omics/data/software/SQANTI3/utilities/IsoAnnotLite_SQ3.py", line 1443, in <module>
    main()
  File "/sc/arion/projects/ad-omics/data/software/SQANTI3/utilities/IsoAnnotLite_SQ3.py", line 1320, in main
    run(args)
  File "/sc/arion/projects/ad-omics/data/software/SQANTI3/utilities/IsoAnnotLite_SQ3.py", line 1382, in run
    mappingFeatures(dc_SQexons, dc_SQcoding, dc_SQtransGene, dc_GFF3exonsTrans, dc_GFF3transExons, dc_GFF3_Genomic, dc_GFF3coding, filename) #edit tappAS_annotation_from_Sqanti file
  File "/sc/arion/projects/ad-omics/data/software/SQANTI3/utilities/IsoAnnotLite_SQ3.py", line 851, in mappingFeatures
    perct = featuresAnnotated/totalAnotations*100
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/sc/arion/projects/ad-omics/data/software/SQANTI3/sqanti3_qc.py", line 2289, in <module>
    main()
  File "/sc/arion/projects/ad-omics/data/software/SQANTI3/sqanti3_qc.py", line 2277, in main
    run_isoAnnotLite(corrGTF, outputClassPath, outputJuncPath, args.dir, args.output, args.gff3)
  File "/sc/arion/projects/ad-omics/data/software/SQANTI3/sqanti3_qc.py", line 1912, in run_isoAnnotLite
    if subprocess.check_call(ISOANNOT_CMD, shell=True)!=0:
  File "/sc/arion/projects/als-omics/conda/envs/SQANTI3.env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python /sc/arion/projects/ad-omics/data/software/SQANTI3/utilities/IsoAnnotLite_SQ3.py /sc/arion/projects/als-omics/microglia_isoseq/isoseq-pipeline/all_samples/SQANTI3_test/all_samples.cupcake.collapsed.filtered_corrected.gtf /sc/arion/projects/als-omics/microglia_isoseq/isoseq-pipeline/all_samples/SQANTI3_test/all_samples.cupcake.collapsed.filtered_classification.txt /sc/arion/projects/als-omics/microglia_isoseq/isoseq-pipeline/all_samples/SQANTI3_test/all_samples.cupcake.collapsed.filtered_junctions.txt -gff3 /sc/arion/projects/ad-omics/data/references/hg38_reference/RefSeq/Homo_sapiens_GRCh38_RefSeq_78.gff3 -d /sc/arion/projects/als-omics/microglia_isoseq/isoseq-pipeline/all_samples/SQANTI3_test -o all_samples.cupcake.collapsed.filtered' returned non-zero exit status 1.
```
I also tried running IsoAnnot separately using the `IsoAnnotLite_SQ3.py` script with my corrected GTF but I get the same error.  Do you have any ideas what I might be doing wrong?

**Comment by JieqiongDai** [comment]
I got the same error message. I tried both fasta and gff input files but neither one works. Would like to see the solutions. Thanks.

**Comment by aarzalluz** [comment]
Hi,

First of all, I apologize for the long time that it has taken for our team to get back to you. 

Even though I am not the maintainer or developer of SQANTI3, I do work on tappAS maintenance and have seen that you have had trouble running IsoAnnotLite. I wanted to let you know [new version of IsoAnnotLite](https://isoannot.tappas.org/isoannot-lite/) is now available in our website. Feel free to try it out and see if your problems are solved after annotating your isoforms using the new script. If not, please do let us know so that we can -finally- troubleshoot the problem.

I hope this helps! 

Best,

Ángeles

**Comment by aarzalluz** [comment]
Closing unless OP provides further info on whether the new version of IsoAnnotLite fixed the issue.
