### ISSUE TITLE
FileNotFoundError: Genome file "/chr_order.txt" does not exist

### ISSUE THREAD

**Issue by francicco** [ConesaLab/SQANTI3#300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you loaded the SQANTI3.env conda environment?

- [ ] I have loaded the SQANTI3.env conda environment

### Problem description

Hi I'm getting this error.
I've checked and it seems like it was fixed in a previous version, I have the latest, the 5.2.1.
Cheers
F
 

### Code sample

```
sqanti3_qc.py --polyA_motif_list $APPS2/SQANTI3-5.2.1/data/polyA_motifs/lepidoptera.polyA_motif.FangEtAl2022.txt --cpus 30 --saturation --report both --window 100 --output $SP.SQANTI3qc --aligner_choice minimap2 \
        --SR_bam $WORK/HeliconiniiProject/RNAseq/Hmel/BAMinput.fofn --coverage $WORK/HeliconiniiProject/RNAseq/Hmel/Hmel.RNA.IsoQuantGTF.Head.SJ.out.tab ${SP}IsoSeq.extended_annotation.OnlyStranded.gtf $GTF $ASSEMBLY
```

### Error

```
Traceback (most recent call last):
  File "/user/work/tk19812/software/SQANTI3-5.2.1/sqanti3_qc.py", line 2525, in <module>
    main()
  File "/user/work/tk19812/software/SQANTI3-5.2.1/sqanti3_qc.py", line 2508, in main
    run(args)
  File "/user/work/tk19812/software/SQANTI3-5.2.1/sqanti3_qc.py", line 1871, in run
    isoforms_info, ratio_TSS_dict = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict, corrGTF)
  File "/user/work/tk19812/software/SQANTI3-5.2.1/sqanti3_qc.py", line 1532, in isoformClassification
    inside_bed, outside_bed = get_TSS_bed(corrGTF, chr_order)
  File "/user/work/tk19812/software/SQANTI3-5.2.1/utilities/short_reads.py", line 151, in get_TSS_bed
    i.sort(g=chr_order, output=inside_sorted)
  File "/user/work/tk19812/scWorkshop/miniforge3/envs/SQANTI3.env/lib/python3.10/site-packages/pybedtools/bedtool.py", line 909, in decorated
    result = method(self, *args, **kwargs)
  File "/user/work/tk19812/scWorkshop/miniforge3/envs/SQANTI3.env/lib/python3.10/site-packages/pybedtools/bedtool.py", line 339, in wrapped
    kwargs = self.check_genome(**kwargs)
  File "/user/work/tk19812/scWorkshop/miniforge3/envs/SQANTI3.env/lib/python3.10/site-packages/pybedtools/bedtool.py", line 1632, in check_genome
    raise FileNotFoundError(msg)
FileNotFoundError: Genome file "/chr_order.txt" does not exist

```

**Comment by lkondratova** [comment]
Hi @francicco ,
could you please provide the whole log file for this run?

**Comment by francicco** [comment]
Hi, I think I managed to get it run thank you!
F
