### ISSUE TITLE
Errors when running sqanti3_qc.py and sqanti3_RulesFilter.py

### ISSUE THREAD

**Issue by emaleckova** [ConesaLab/SQANTI3#32]
Hello,

I would like to ask you for help by pointing me out to where the errors I am experiencing might come from. To start with, let me assure you I followed the installation instruction. I also have cDNA_Cupcake available and added it to the PYTHONPATH by running the following two commands after activating the created environment:
`export PYTHONPATH=$PYTHONPATH:/home/bin/cDNA_Cupcake/sequence/`
`export PYTHONPATH=$PYTHONPATH:/home/bin/cDNA_Cupcake/`

However, when trying to run `python sqanti3_qc.py -h`, the following error pops up:
```
Traceback (most recent call last):
  File "/home/eva/SQANTI3/sqanti3_qc.py", line 51, in <module>
    from err_correct_w_genome import err_correct
  File "/home/eva/cDNA_Cupcake/sequence/err_correct_w_genome.py", line 9, in <module>
    import BioReaders
  File "/home/eva/cDNA_Cupcake/sequence/BioReaders.py", line 419
    print "qStart:", self.qStart
                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("qStart:", self.qStart)?
```

Similarly, `python sqanti3_RulesFilter.py` returns:
```
Traceback (most recent call last):
  File "sqanti3_RulesFilter.py", line 17, in <module>
    from cupcake.io.BioReaders import GMAPSAMReader
  File "/home/eva/cDNA_Cupcake/cupcake/io/BioReaders.py", line 311
    raise Exception, "Unrecognized cigar character {0}!".format(type)
                   ^
SyntaxError: invalid syntax
```

I am wondering whether this has something to do with my python version, which should be Python 3.7.6.

Did something go wrong while preparing the environment or installing any of the dependencies? How should I solve this problem?

Thank you very much.

**Comment by emaleckova** [comment]
OK, it was my fault. I had an old installation of cDNA_Cupcake. After downloading the script repository again and adding to the path as in the SQANTI instructions, it now works just fine. Sorry.
