### ISSUE TITLE
error orf , terminate called after throwing an instance of 'std::length_error'

### ISSUE THREAD

**Issue by BeatrizdeToledo** [ConesaLab/SQANTI3#47]
Good afternoon, 
I tried to run sqanti with a gtf file generated from stringtie+PACBIO gtf. With only pacbio gtf works perfectly.

The command
singularity exec -B /group/calegari_beatrizepi/combinedgtf /projects/globalscratch/sqanti3.sif sqanti3_qc.py  merged.a25.all.others.10.d.nofus.merge.annotated.filteredrename.gtf Mus_musculus.GRCm38.101.gtf Mus_musculus.GRCm38.dna.primary_assembly.fa --cage_peak mm10_fair_new_CAGE_peaks_phase1and2.bed --polyA_motif_list PolyA_motif_List_mm10.txt --gtf -o ALL -c DP_L356_twopassSJ.out.tab,DP_L223_twopassSJ.out.tab,DP_L394_twopassSJ.out.tab,N_L357_twopassSJ.out.tab,N_L224_twopassSJ.out.tab,N_L395_twopassSJ.out.tab,PP_L355_twopassSJ.out.tab,PP_L222_twopassSJ.out.tab,PP_L393_twopassSJ.out.tab --isoAnnotLite --gff3 Mus_musculus_GRCm38_Ensembl_86.gff3

head of the gtf file (I renamed to have PB id)
1       PacBio  transcript      4807829 4846734 .       +       .       gene_id "PB.3"; transcript_id "PB.3.1";
1       PacBio  exon    4807829 4807982 .       +       .       gene_id "PB.3"; transcript_id "PB.3.1";
1       PacBio  exon    4808455 4808486 .       +       .       gene_id "PB.3"; transcript_id "PB.3.1";
1       PacBio  exon    4828584 4828649 .       +       .       gene_id "PB.3"; transcript_id "PB.3.1";
1       PacBio  exon    4830268 4830315 .       +       .       gene_id "PB.3"; transcript_id "PB.3.1";
1       PacBio  exon    4832311 4832381 .       +       .       gene_id "PB.3"; transcript_id "PB.3.1";

The error
**** Parsing provided files....
Reading genome fasta /group/calegari_beatrizepi/combinedgtf/Mus_musculus.GRCm38.dna.primary_assembly.fa....
Error corrected FASTA /group/calegari_beatrizepi/combinedgtf/ALL_corrected.fasta already exists. Using it...
**** Predicting ORF sequences...
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_S_create
GeneMarkS: error on last system call, error code 134
Abort program!!!
Traceback (most recent call last):
  File "/SQANTI3/sqanti3_qc.py", line 2267, in <module>
    main()
  File "/SQANTI3/sqanti3_qc.py", line 2260, in main
    run(args)
  File "/SQANTI3/sqanti3_qc.py", line 1691, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "/SQANTI3/sqanti3_qc.py", line 593, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/miniconda3/envs/SQANTI3.env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl /SQANTI3/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /group/calegari_beatrizepi/combinedgtf/GMST/GMST_tmp /group/calegari_beatrizepi/combinedgtf/ALL_corrected.fasta' returned non-zero exit status 1.

Any idea of what would cause this?
Thank you

**Comment by BeatrizdeToledo** [comment]
for some reason the stringtie generated transcripts with exons with exactly same start and end coordinates, so i deleted these transcripts and it worked.
