### ISSUE TITLE
error using GFF or converted GTF

### ISSUE THREAD

**Issue by noor-albader** [ConesaLab/SQANTI3#49]
Hi 
I accidentally open a ticket with SQANTI2 instead of SQANTI3so I decided to re-post here (sorry for the duplication!):

I am using sqanti3 with the following parameters :
```
Version 2.0.0
Input   all_samples.chained.gff
Annotation      OcoaRS1.PZYT01.fa.all.maker.functional_ipr.gff
Genome  OcoaRS1.PZYT01.fa.masked
Aligner minimap2
FLCount all_samples.chained_count.txt
Expression      transcript_tpms_all_samples.tsv
Junction        *SJ.tab.out
CagePeak        NA
PolyA   NA
PolyAPeak       NA
IsFusion        False
```

The script I am running: 

```
sqanti3_qc.py --gtf /home/albadenm/c2042/analysis/IsoSeq_Ocoarcata/chain_filtered_isoseq_3/all_samples.chained.gff \
/home/albadenm/c2042/analysis/IsoSeq_Ocoarcata/maker/OcoaRS1.PZYT01.fa.maker.output/round4/OcoaRS1.PZYT01.fa.all.maker.functional_ipr.gff \
/home/albadenm/c2042/analysis/IsoSeq_Ocoarcata/maker/OcoaRS1.PZYT01.fa.maker.output/round4/OcoaRS1.PZYT01.fa.masked \
--fl_count /home/albadenm/c2042/analysis/IsoSeq_Ocoarcata/chain_filtered_isoseq_3/all_samples.chained_count.txt \
-c star/*SJ.tab.out --expression rsem_exp/GeneMat.txt --isoAnnotLite -t 128 -n 8
```

But get this error (a directory named `splits/`, with subdirectories 0/ to 7/, are created, however the contents of the subdirectory are unequal (not all contain a *.faa) and all other output files are empty) :

```
R scripting front-end version 3.6.1 (2019-07-05)
Write arguments to /ibex/scratch/projects/c2042/analysis/sqanti3/all_samples.chained.params.txt...
**** Running SQANTI3...
launching worker on on splits/0/all_samples.chained.gff.split0....
launching worker on on splits/1/all_samples.chained.gff.split1....
**** Parsing provided files....
Reading genome fasta /home/albadenm/c2042/analysis/IsoSeq_Ocoarcata/maker/OcoaRS1.PZYT01.fa.maker.output/round4/OcoaRS1.PZYT01.fa.masked....
launching worker on on splits/2/all_samples.chained.gff.split2....
**** Parsing provided files....
Reading genome fasta /home/albadenm/c2042/analysis/IsoSeq_Ocoarcata/maker/OcoaRS1.PZYT01.fa.maker.output/round4/OcoaRS1.PZYT01.fa.masked....
launching worker on on splits/3/all_samples.chained.gff.split3....
**** Parsing provided files....
Reading genome fasta /home/albadenm/c2042/analysis/IsoSeq_Ocoarcata/maker/OcoaRS1.PZYT01.fa.maker.output/round4/OcoaRS1.PZYT01.fa.masked....
launching worker on on splits/4/all_samples.chained.gff.split4....
**** Parsing provided files....
Reading genome fasta /home/albadenm/c2042/analysis/IsoSeq_Ocoarcata/maker/OcoaRS1.PZYT01.fa.maker.output/round4/OcoaRS1.PZYT01.fa.masked....
launching worker on on splits/5/all_samples.chained.gff.split5....
**** Parsing provided files....
Reading genome fasta /home/albadenm/c2042/analysis/IsoSeq_Ocoarcata/maker/OcoaRS1.PZYT01.fa.maker.output/round4/OcoaRS1.PZYT01.fa.masked....
launching worker on on splits/6/all_samples.chained.gff.split6....
**** Parsing provided files....
Reading genome fasta /home/albadenm/c2042/analysis/IsoSeq_Ocoarcata/maker/OcoaRS1.PZYT01.fa.maker.output/round4/OcoaRS1.PZYT01.fa.masked....
launching worker on on splits/7/all_samples.chained.gff.split7....
**** Parsing provided files....
Reading genome fasta /home/albadenm/c2042/analysis/IsoSeq_Ocoarcata/maker/OcoaRS1.PZYT01.fa.maker.output/round4/OcoaRS1.PZYT01.fa.masked....
**** Parsing provided files....
Reading genome fasta /home/albadenm/c2042/analysis/IsoSeq_Ocoarcata/maker/OcoaRS1.PZYT01.fa.maker.output/round4/OcoaRS1.PZYT01.fa.masked....
Skipping aligning of sequences because GTF file was provided.
Skipping aligning of sequences because GTF file was provided.
Skipping aligning of sequences because GTF file was provided.
Skipping aligning of sequences because GTF file was provided.
Skipping aligning of sequences because GTF file was provided.
Skipping aligning of sequences because GTF file was provided.
Skipping aligning of sequences because GTF file was provided.
Skipping aligning of sequences because GTF file was provided.

Indels will be not calculated since you ran SQANTI3 without alignment step (SQANTI3 with gtf format as transcriptome input).

Indels will be not calculated since you ran SQANTI3 without alignment step (SQANTI3 with gtf format as transcriptome input).

Indels will be not calculated since you ran SQANTI3 without alignment step (SQANTI3 with gtf format as transcriptome input).

Indels will be not calculated since you ran SQANTI3 without alignment step (SQANTI3 with gtf format as transcriptome input).
**** Predicting ORF sequences...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").

Indels will be not calculated since you ran SQANTI3 without alignment step (SQANTI3 with gtf format as transcriptome input).
**** Predicting ORF sequences...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
**** Predicting ORF sequences...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
**** Predicting ORF sequences...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").

Indels will be not calculated since you ran SQANTI3 without alignment step (SQANTI3 with gtf format as transcriptome input).
**** Predicting ORF sequences...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").

Indels will be not calculated since you ran SQANTI3 without alignment step (SQANTI3 with gtf format as transcriptome input).
**** Predicting ORF sequences...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").

Indels will be not calculated since you ran SQANTI3 without alignment step (SQANTI3 with gtf format as transcriptome input).
**** Predicting ORF sequences...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
**** Predicting ORF sequences...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
error: data input empty 
GeneMarkS: error on last system call, error code 256
Abort program!!!
Process Process-1:
Traceback (most recent call last):
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 1748, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 583, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl /ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /ibex/scratch/projects/c2042/analysis/sqanti3/splits/0/GMST/GMST_tmp /ibex/scratch/projects/c2042/analysis/sqanti3/splits/0/all_samples.chained_corrected.fasta' returned non-zero exit status 1.
**** Parsing Reference Transcriptome....
/home/albadenm/c2042/analysis/IsoSeq_Ocoarcata/maker/OcoaRS1.PZYT01.fa.maker.output/round4/OcoaRS1.PZYT01.fa.all.maker.functional_ipr.gff doesn't appear to be a GTF file (GFF not supported by this program)
Process Process-8:
Traceback (most recent call last):
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 1751, in run
    refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene = reference_parser(args, list(genome_dict.keys()))
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 653, in reference_parser
    for r in genePredReader(referenceFiles):
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 134, in __init__
    self.f = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/ibex/scratch/projects/c2042/analysis/sqanti3/splits/7/refAnnotation_all_samples.chained.genePred'
**** Parsing Reference Transcriptome....
/home/albadenm/c2042/analysis/IsoSeq_Ocoarcata/maker/OcoaRS1.PZYT01.fa.maker.output/round4/OcoaRS1.PZYT01.fa.all.maker.functional_ipr.gff doesn't appear to be a GTF file (GFF not supported by this program)
Process Process-3:
Traceback (most recent call last):
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 1751, in run
    refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene = reference_parser(args, list(genome_dict.keys()))
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 653, in reference_parser
    for r in genePredReader(referenceFiles):
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 134, in __init__
    self.f = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/ibex/scratch/projects/c2042/analysis/sqanti3/splits/2/refAnnotation_all_samples.chained.genePred'
**** Parsing Reference Transcriptome....
/home/albadenm/c2042/analysis/IsoSeq_Ocoarcata/maker/OcoaRS1.PZYT01.fa.maker.output/round4/OcoaRS1.PZYT01.fa.all.maker.functional_ipr.gff doesn't appear to be a GTF file (GFF not supported by this program)
Process Process-3:
Traceback (most recent call last):
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 1751, in run
    refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene = reference_parser(args, list(genome_dict.keys()))
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 653, in reference_parser
    for r in genePredReader(referenceFiles):
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 134, in __init__
    self.f = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/ibex/scratch/projects/c2042/analysis/sqanti3/splits/2/refAnnotation_all_samples.chained.genePred'
^[[B**** Parsing Reference Transcriptome....
/home/albadenm/c2042/analysis/IsoSeq_Ocoarcata/maker/OcoaRS1.PZYT01.fa.maker.output/round4/OcoaRS1.PZYT01.fa.all.maker.functional_ipr.gff doesn't appear to be a GTF file (GFF not supported by this program)
Process Process-4:
Traceback (most recent call last):
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 1751, in run
    refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene = reference_parser(args, list(genome_dict.keys()))
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 653, in reference_parser
    for r in genePredReader(referenceFiles):
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 134, in __init__
    self.f = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/ibex/scratch/projects/c2042/analysis/sqanti3/splits/3/refAnnotation_all_samples.chained.genePred'
error: data input empty 
GeneMarkS: error on last system call, error code 256
Abort program!!!
Process Process-7:
Traceback (most recent call last):
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 1748, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 583, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl /ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /ibex/scratch/projects/c2042/analysis/sqanti3/splits/6/GMST/GMST_tmp /ibex/scratch/projects/c2042/analysis/sqanti3/splits/6/all_samples.chained_corrected.fasta' returned non-zero exit status 1.
error: data input empty 
GeneMarkS: error on last system call, error code 256
Abort program!!!
Process Process-5:
Traceback (most recent call last):
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 1748, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 583, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl /ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /ibex/scratch/projects/c2042/analysis/sqanti3/splits/4/GMST/GMST_tmp /ibex/scratch/projects/c2042/analysis/sqanti3/splits/4/all_samples.chained_corrected.fasta' returned non-zero exit status 1.
error: data input empty 
GeneMarkS: error on last system call, error code 256
Abort program!!!
Process Process-6:
Traceback (most recent call last):
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 1748, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 583, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl /ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /ibex/scratch/projects/c2042/analysis/sqanti3/splits/5/GMST/GMST_tmp /ibex/scratch/projects/c2042/analysis/sqanti3/splits/5/all_samples.chained_corrected.fasta' returned non-zero exit status 1.
error: data input empty 
GeneMarkS: error on last system call, error code 256
Abort program!!!
Process Process-2:
Traceback (most recent call last):
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 1748, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 583, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl /ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /ibex/scratch/projects/c2042/analysis/sqanti3/splits/1/GMST/GMST_tmp /ibex/scratch/projects/c2042/analysis/sqanti3/splits/1/all_samples.chained_corrected.fasta' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 2337, in <module>
    main()
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 2328, in main
    combine_split_runs(args, split_dirs)
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 2151, in combine_split_runs
    with open(_orf) as h: f_faa.write(h.read())
FileNotFoundError: [Errno 2] No such file or directory: '/ibex/scratch/projects/c2042/analysis/sqanti3/splits/0/all_samples.chained_corrected.faa'
```

Any help or insight would be greatly appreciated :)

**Comment by noor-albader** [comment]
OH! and I also tried converting my gff to gtf using `gffread  all_samples.chained.gff -T -o all_samples.gtf `and then running sqanti3 on the gtf instead of the gff output of cupcake collapse but get a similar errors as others (i.e. ticket #35 in SQANTI2 repo):

```
Loading module for SQANTI3
SQANTI3 1.6 is now loaded
R scripting front-end version 3.6.1 (2019-07-05)
Traceback (most recent call last):
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 2337, in <module>
    main()
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 2327, in main
    split_dirs = split_input_run(args)
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 2085, in split_input_run
    recs = [r for r in collapseGFFReader(args.isoforms)]
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/SQANTI3/sqanti3_qc.py", line 2085, in <listcomp>
    recs = [r for r in collapseGFFReader(args.isoforms)]
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/site-packages/cupcake-19.0.0-py3.7-linux-x86_64.egg/cupcake/io/GFF.py", line 408, in __next__
    return self.read()
  File "/ibex/sw/csi/sqanti3/1.6/el7.9_conda3/miniconda3/envs/SQANTI3.env/lib/python3.7/site-packages/cupcake-19.0.0-py3.7-linux-x86_64.egg/cupcake/io/GFF.py", line 579, in read
    assert raw[2] == 'transcript'
AssertionError
```

**Comment by FJPardoPalacios** [comment]
Sorry for the late response. But I think I know what is happening. 

For the first issue, it seems that there is aproblem with your perl local settings:

`perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").`

For the second case, if your "all_samples.chained.gff" file was obtained through IsoSeq3 or cDNA Cupcake scripts, you don't need to convert your GFF to GTF. In fact, your GFF is in GFF2 format, which is the same than GTF.

**Comment by Magdoll** [comment]
Hi @noor-albader 
This looks like a input GTF/GFF3 format issue to me (though I could be wrong)
Any chance you can share the input GTF?
If so plz provide email so I can request data upload

Thanks!
-Liz

**Comment by noor-albader** [comment]
Hi @Magdoll 
Yes please, my email is noor.albader@kaust.edu.sa 
I am using the GFF from chain_samples and a reference converted from GFF to GTF using `gffread`. 

I can send all three files (chain_Samples.GFF, ref.GFF and ref.GTF).

**Comment by noor-albader** [comment]
HI @FJPardoPalacios 
Its alright, thank you for getting back to me! 
The perl warning is removed once `$ LANG=C perl -e exit` is placed in my SQANTI3 script. But the remainder of the error is the same. I also tried the newest SQANTI3 version, the errors persists. Maybe it is the GFF format as @Magdoll suggests?

Thank you!

**Comment by Magdoll** [comment]
This particular issue has been solved by using `--skipORF` and providing properly formatted input chained count files.
