### ISSUE TITLE
Error: "Expected GMST output IDs to be of format:" 

### ISSUE THREAD

**Issue by mchimenti** [ConesaLab/SQANTI3#50]
Hello, 
I am trying to run SQANTI3 'sqanti_qc.py' on the output of cupcake 'collapse' as an SGE job: 

```
#!/bin/bash
#$ -pe smp 28
#$ -S /bin/bash
#$ -cwd
#$ -M michael-chimenti@uiowa.edu
#$ -m aes
#$ -j y

source activate SQANTI3.env

export PYTHONPATH=$PYTHONPATH:/Users/mchiment/cDNA_Cupcake

python ~/SQANTI3/sqanti3_qc.py --gtf ../cupcake/transcripts.collapsed.min_fl_10.gff \
                               ../GRCm39/GCF_000001635.27_GRCm39_genomic.gtf \
                               ../GRCm39/GCF_000001635.27_GRCm39_genomic.fna \
                               -o test

```
Input transcripts from cupcake look like this: 
```
NC_000067.7	PacBio	transcript	4561611	4563831	.	-	.	gene_id "PB.2"; transcript_id "PB.2.3";
NC_000067.7	PacBio	exon	4561611	4562891	.	-	.	gene_id "PB.2"; transcript_id "PB.2.3";
NC_000067.7	PacBio	exon	4563323	4563831	.	-	.	gene_id "PB.2"; transcript_id "PB.2.3";
NC_000067.7	PacBio	transcript	4846602	4855921	.	-	.	gene_id "PB.3"; transcript_id "PB.3.4";
NC_000067.7	PacBio	exon	4846602	4847024	.	-	.	gene_id "PB.3"; transcript_id "PB.3.4";
NC_000067.7	PacBio	exon	4847748	4847871	.	-	.	gene_id "PB.3"; transcript_id "PB.3.4";
NC_000067.7	PacBio	exon	4852791	4852956	.	-	.	gene_id "PB.3"; transcript_id "PB.3.4";
NC_000067.7	PacBio	exon	4854174	4854328	.	-	.	gene_id "PB.3"; transcript_id "PB.3.4";
NC_000067.7	PacBio	exon	4855796	4855921	.	-	.	gene_id "PB.3"; transcript_id "PB.3.4";
```
The python code errors out with a `sys.exit()` on this: 

```
Expected GMST output IDs to be of format 

'<pbid> gene_4|GeneMark.hmm|<orf>_aa|<strand>|<cds_start>|<cds_end>’ 

but instead saw: 

PB.2.3 gene=PB.2    gene_1|GeneMark.hmm|419_aa|+|203|1462.   

! Abort!
```
Which I believe is coming from line ~586 of the SQANTI3 code: 
```

        # Modifying ORF sequences by removing sequence before ATG
        with open(corrORF, "w") as f:
            for r in SeqIO.parse(open(gmst_pre+'.faa'), 'fasta'):
                m = gmst_rex.match(r.description)
                if m is None:
                    print("Expected GMST output IDs to be of format '<pbid> gene_4|GeneMark.hmm|<orf>_aa|<strand>|<cds_start>|<cds_end>' but instead saw: {0}! Abort!".format(r.description), file=sys.stderr)
                    sys.exit(-1)
```
A head on the GMST_tmp.faa file looks like this: 

```
>PB.2.3 gene=PB.2	gene_1|GeneMark.hmm|419_aa|+|203|1462
MSSPDAGYASDDQSQPRSAQPAVMAGLGPCPWAESLSPLGDVKVKGEVVASSGAPAGTSG
RAKAESRIRRPMNAFMVWAKDERKRLAQQNPDLHNAELSKMLGKSWKALTLAEKRPFVEE
AERLRVQHMQDHPNYKYRPRRRKQVKRMKRVEGGFLHALVEPQAGALGPEGGRVAMDGLG
LPFPEPGYPAGPPLMSPHMGPHYRDCQGLGAPALDGYPLPTPDTSPLDGVEQDPAFFAAP
LPGDCPAAGTYTYAPVSDYAVSVEPPAGPMRVGPDPSGPAMPGILAPPSALHLYYGAMGS
PAASAGRGFHAQPQQPLQPQAPPPPPQQQHPAHGPGQPSPPPEALPCRDGTESNQPTELL
GEVDRTEFEQYLPFVYKPEMGLPYQGHDCGVNLSDSHGAISSVVSDASSAVYYCNYPDI

>PB.3.4 gene=PB.3	gene_2|GeneMark.hmm|302_aa|+|1|909
```
And there is indeed the "gene=PB.3" field which is not supposed to be there according to the code.  I could try using VIM to delete this field from the "GMST_tmp.faa" file and running again?  My input GFF file looks exactly like the example file, so it must be a problem with the GMST code base, I think.  

Any insight on how to proceed would be appreciated.  Thanks!

**Comment by mchimenti** [comment]
UPDATE:  I tried a 'hack' by hand editing the GMST_tmp.faa file using VI.  

Input: 
```
>PB.2.3 gene=PB.2    gene_1|GeneMark.hmm|419_aa|+|203|1462
MSSPDAGYASDDQSQPRSAQPAVMAGLGPCPWAESLSPLGDVKVKGEVVASSGAPAGTSG
RAKAESRIRRPMNAFMVWAKDERKRLAQQNPDLHNAELSKMLGKSWKALTLAEKRPFVEE
AERLRVQHMQDHPNYKYRPRRRKQVKRMKRVEGGFLHALVEPQAGALGPEGGRVAMDGLG
LPFPEPGYPAGPPLMSPHMGPHYRDCQGLGAPALDGYPLPTPDTSPLDGVEQDPAFFAAP
LPGDCPAAGTYTYAPVSDYAVSVEPPAGPMRVGPDPSGPAMPGILAPPSALHLYYGAMGS
PAASAGRGFHAQPQQPLQPQAPPPPPQQQHPAHGPGQPSPPPEALPCRDGTESNQPTELL
GEVDRTEFEQYLPFVYKPEMGLPYQGHDCGVNLSDSHGAISSVVSDASSAVYYCNYPDI
```
After editing in VI: 
```
>PB.2.3    gene_1|GeneMark.hmm|419_aa|+|203|1462
MSSPDAGYASDDQSQPRSAQPAVMAGLGPCPWAESLSPLGDVKVKGEVVASSGAPAGTSG
RAKAESRIRRPMNAFMVWAKDERKRLAQQNPDLHNAELSKMLGKSWKALTLAEKRPFVEE
AERLRVQHMQDHPNYKYRPRRRKQVKRMKRVEGGFLHALVEPQAGALGPEGGRVAMDGLG
LPFPEPGYPAGPPLMSPHMGPHYRDCQGLGAPALDGYPLPTPDTSPLDGVEQDPAFFAAP
LPGDCPAAGTYTYAPVSDYAVSVEPPAGPMRVGPDPSGPAMPGILAPPSALHLYYGAMGS
PAASAGRGFHAQPQQPLQPQAPPPPPQQQHPAHGPGQPSPPPEALPCRDGTESNQPTELL
GEVDRTEFEQYLPFVYKPEMGLPYQGHDCGVNLSDSHGAISSVVSDASSAVYYCNYPDI
```

Restarting SQANTI3 'sqanti3_qc.py' after this edit appears to allow the code to bypass this problem with the REGEX mismatch.  The log has: 

```
R scripting front-end version 3.6.1 (2019-07-05)
invalid gffGroup detected on line: NC_000072.7	Curated Genomic	stop_codon	41534627	41534629	0.000000	-	0	gene_id "Trbv31"; transcript_id "unknown_transcript_1";
GFF/GTF group unknown_transcript_1 on NC_000072.7+, this line is on NC_000072.7-, all group members must be on same seq and strand
1 errors
Error corrected FASTA /Shared/Bioinformatics/data/mchiment/cui/project_pacbio_isoseq_mar2021/SQANTI3/test_corrected.fasta already exists. Using it...
ORF file /Shared/Bioinformatics/data/mchiment/cui/project_pacbio_isoseq_mar2021/SQANTI3/test_corrected.faa already exists. Using it....
WARNING: All input isoforms were predicted as non-coding
**** Parsing Isoforms....
Write arguments to /Shared/Bioinformatics/data/mchiment/cui/project_pacbio_isoseq_mar2021/SQANTI3/test.params.txt...
**** Running SQANTI3...
**** Parsing provided files....
Reading genome fasta /Shared/Bioinformatics/data/mchiment/cui/project_pacbio_isoseq_mar2021/GRCm39/GCF_000001635.27_GRCm39_genomic.fna....
**** Predicting ORF sequences...
**** Parsing Reference Transcriptome....
Splice Junction Coverage files not provided.
**** Performing Classification of Isoforms....
Number of classified isoforms: 19969
```

But then: 
```
Traceback (most recent call last):
  File "/Users/mchiment/SQANTI3/sqanti3_qc.py", line 2337, in <module>
    main()
  File "/Users/mchiment/SQANTI3/sqanti3_qc.py", line 2321, in main
    run(args)
  File "/Users/mchiment/SQANTI3/sqanti3_qc.py", line 1770, in run
    write_collapsed_GFF_with_CDS(isoforms_info, corrGTF, corrGTF+'.cds.gff')
  File "/Users/mchiment/SQANTI3/sqanti3_qc.py", line 413, in write_collapsed_GFF_with_CDS
    for r in reader:
  File "/Users/mchiment/cDNA_Cupcake/cupcake/io/GFF.py", line 408, in __next__
    return self.read()
  File "/Users/mchiment/cDNA_Cupcake/cupcake/io/GFF.py", line 579, in read
    assert raw[2] == 'transcript'
AssertionError
```

I'm not sure if this further error is related to the previous error.  Thanks.

**Comment by mchimenti** [comment]
Would it be possible to get a response on this issue(s)?  Any help is appreciated.  Thanks.
