### ISSUE TITLE
GMST path not writeable

### ISSUE THREAD

**Issue by HeyLifeHD** [ConesaLab/SQANTI3#74]
Dear SQANTI3 authors,
I started using SQUANTI3 yesterday and was facing a minor problem this morning. It seems as if the GMST folder, generated by SQANTI3 is not writeable. The tools seem to be running upon the second trial but repeatedly crashes during the first attempt. 

`
**** Predicting ORF sequences...
error: , /omics/groups/OE0219/internal/tinat/210708_integrated_deNovo_analysis/GMST not writable
Traceback (most recent call last):
  File "/home/heyj/tools/SQANTI3-4.1/sqanti3_qc.py", line 2486, in <module>
    main()
  File "/home/heyj/tools/SQANTI3-4.1/sqanti3_qc.py", line 2470, in main
    run(args)
  File "/home/heyj/tools/SQANTI3-4.1/sqanti3_qc.py", line 1863, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "/home/heyj/tools/SQANTI3-4.1/sqanti3_qc.py", line 583, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/home/heyj/miniconda3/envs/SQANTI3.env/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl /home/heyj/tools/SQANTI3-4.1/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /omics/groups/OE0219/internal/tinat/210708_integrated_deNovo_analysis/GMST/GMST_tmp /omics/groups/OE0219/internal/tinat/210708_integrated_deNovo_analysis/210708_DACandSB939_short_corrected.fasta' returned non-zero exit status 1.
`

Thanks for your support. 

Best wishes,

Joschka

**Comment by HeyLifeHD** [comment]
Sorry. This Error was most likely due to a change in our server mounts.
