### ISSUE TITLE
Error in gmst.pl

### ISSUE THREAD

**Issue by ndrubins** [ConesaLab/SQANTI3#95]
Hi,

I'm running `SQANTI3`'s `sqanti3_qc.py`, as part of the [cDNA_Cupcake](https://github.com/Magdoll/cDNA_Cupcake/wiki/Iso-Seq-Single-Cell-Analysis:-Recommended-Analysis-Guidelines#ccs) workflow. My command is:
`sqanti3_qc.py -fl <PB_abundance> <isoforms> <annotation> <genome>`

And I'm getting these messages:
```
R scripting front-end version 3.6.1 (2019-07-05)
Write arguments to /data/ccs_filtered_demuxed/m_2m_1/demultiplex.bc1027--bc1027.dedup.5merge.collapsed.params.txt...
**** Running SQANTI3...
**** Parsing provided files....
Reading genome fasta /data/references/mus_mus/mm10/sequences/GRCm38.p6.genome.fa....
Skipping aligning of sequences because GTF file was provided.

Indels will be not calculated since you ran SQANTI3 without alignment step (SQANTI3 with gtf format as transcriptome input).
**** Predicting ORF sequences...
error in command line
GeneMarkS: error on last system call, error code 256
Abort program!!!
Traceback (most recent call last):
  File "/home/nrb/git_repos/SQANTI3/sqanti3_qc.py", line 2461, in <module>
    main()
  File "/home/nrb/git_repos/SQANTI3/sqanti3_qc.py", line 2444, in main
    run(args)
  File "/home/nrb/git_repos/SQANTI3/sqanti3_qc.py", line 1836, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "/home/nrb/git_repos/SQANTI3/sqanti3_qc.py", line 594, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/home/nrb/miniconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl /home/nrb/git_repos/SQANTI3/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /data/ccs_filtered_demuxed/m_2m_1/GMST/GMST_tmp /data/ccs_filtered_demuxed/m_2m_1/demultiplex.bc1027--bc1027.dedup.5merge.collapsed_corrected.fasta' returned non-zero exit status 1.

```

The sequence file: `/data/ccs_filtered_demuxed/m_2m_1/demultiplex.bc1027--bc1027.dedup.5merge.collapsed_corrected.fasta` exists and has 5974 sequences.

Any idea?

Thanks

**Comment by ndrubins** [comment]
Seems to be caused by the "--" in the file name I'm using.
